### ISSUE TITLE
Undefined function 'abcd'

### ISSUE THREAD

**Issue by zeus420** [Shikhar1998/Stock-Market-Prediction-using-Neural-Networks-and-Genetic-Algorithm#11]
When running optimtool, getting the error "Undefined function 'abcd' for input arguments of type 'double'".

**Comment by zeus420** [comment]
Can you write down this fitness function?

**Comment by keyurrohit** [comment]
Sir, please resolve this issue.

**Comment by Shikhar1998** [comment]
@keyurrohit, @zeus420 sorry for the late reply. Try replacing the function name `main` with `abcd`. Also, rename the file to `abcd.m` from `main.m`

**Comment by Shikhar1998** [comment]
Also, check for the `optimization function` you are using. It should be `Multi-objective Genetic Algorithm`.

**Comment by zeus420** [comment]
I called the function "main" in the example and that did the trick. Thanks!
