### ISSUE TITLE
Infinite run

### ISSUE THREAD

**Issue by keyurrohit** [Shikhar1998/Stock-Market-Prediction-using-Neural-Networks-and-Genetic-Algorithm#12]
After clicking the start in the optimization toolbox, it keeps on doing the iterations. After completion of 8000 epochs, it stars again. It never stops. Please resolve this, sir!

**Comment by Shikhar1998** [comment]
This method is time `intensive`. You can get approximate results by changing `8000 epochs` to `4000` or `2000`
