### ISSUE TITLE
What should be the fitness function in Optimization toolbox?

### ISSUE THREAD

**Issue by keyurrohit** [Shikhar1998/Stock-Market-Prediction-using-Neural-Networks-and-Genetic-Algorithm#9]
Also, what is the number of variables?

**Comment by Shikhar1998** [comment]
The fitness function should be `@abcd` while, the number of nodes should be `1`.
For more details you can refer to the figure [here.](https://github.com/Shikhar1998/Stock-Market-Prediction-using-Neural-Networks-and-Genetic-Algorithm/blob/master/Figures/3.png)

**Comment by keyurrohit** [comment]
Optimization running.
Error running optimization.
Undefined function 'abcd' for input arguments of type 'double'.

**Comment by zeus420** [comment]
Same problem here. It seems the function abcd is missing. Can't go any further...

**Comment by prateekdaniels** [comment]
@keyurrohit : same here. I got the same error

**Comment by prateekdaniels** [comment]
@Shikhar1998 : Nice work bro. But what would be the function here ? @abcd ?

**Comment by Shikhar1998** [comment]
https://github.com/Shikhar1998/Stock-Market-Prediction-using-Neural-Networks-and-Genetic-Algorithm/issues/11
